language: php

sudo: false

php:
  - '7.1'
  - '7.2'

services:
  - docker
  - mysql

before_install:
  - docker pull ubuntu

install:
  - composer install
  - mysql -e 'CREATE DATABASE larabuild_testing;'
  - cp .env.travis .env.testing
  - php artisan passport:keys

cache:
  directories:
    - $HOME/.cache/composer/files
    - $HOME/.composer/cache/files
