version: '2.3'

services:
  app:
    build: .
    image: larabuild_app
    user: root
    command: ['/usr/sbin/php-fpm7.2']
    env_file: .env.testing
    environment:
      - DB_HOST=test_db
    restart: unless-stopped
    volumes:
      - ./:/workspace
    depends_on:
      test_db:
        condition: service_healthy

  test_db:
    image: mariadb:10.1-bionic
    env_file: .env.testing
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306
    restart: unless-stopped
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/127.0.0.1/3306 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
