#
# Built with https://github.com/datashaman/docker-laravel
#
# Packages: beanstalkd google-chrome mailhog memcached mysql redis php7.2 node11
#

version: '3.4'

services:
  beanstalkd:
    image: schickling/beanstalkd
    command: -b /var/lib/beanstalkd
    volumes:
      - beanstalkd:/var/lib/beanstalkd

  beanstalkd-console:
    image: schickling/beanstalkd-console
    command: php -S 0.0.0.0:2080 -t /source/public
    environment:
      - BEANSTALK_SERVERS=beanstalkd:11300
    ports:
      - 2080:2080
    depends_on:
      - beanstalkd

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025

  db:
    image: mysql:5.7
    env_file: .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  memcached:
    image: memcached:1.5-alpine

  redis:
    image: redis:4-alpine
    volumes:
      - redis:/data

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis

  web:
    image: nginx:stable
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./:/workspace
      - ./templates/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build: .
    user: root
    command: ['/usr/sbin/php-fpm7.2']
    env_file: .env
    environment:
      - DB_HOST=db
      - MAIL_DRIVER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MEMCACHED_HOST=memcached
      - QUEUE_HOST=beanstalkd
      - REDIS_HOST=redis
    depends_on:
      - beanstalkd
      - db
      - mailhog
      - memcached
      - redis
    volumes:
      - ./:/workspace

  worker:
    build: .
    command: ['php', 'artisan', 'queue:work', '--tries=1', '-vv']
    env_file: .env
    environment:
      - DB_HOST=db
      - MAIL_DRIVER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MEMCACHED_HOST=memcached
      - QUEUE_HOST=beanstalkd
      - REDIS_HOST=redis
    depends_on:
      - beanstalkd
      - db
      - mailhog
      - memcached
      - redis
    volumes:
      - ./:/workspace

volumes:
  beanstalkd:
  mysql:
  redis:
