version: '2'

services:
  app:
    build: .
    image: larabuild_app
    user: root
    command: ['/usr/sbin/php-fpm7.2']
    env_file: .env.local
    environment:
      - DB_HOST=db
      - MAIL_DRIVER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MEMCACHED_HOST=memcached
      - REDIS_HOST=redis
    restart: unless-stopped
    volumes:
      - ./:/workspace
    depends_on:
      - db
      - mailhog
      - memcached
      - redis

  db:
    image: mysql:5.7
    env_file: .env.local
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  horizon:
    image: larabuild_app
    command: ['php', 'artisan', 'horizon']
    env_file: .env.local
    environment:
      - DB_HOST=db
      - MAIL_DRIVER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MEMCACHED_HOST=memcached
      - REDIS_HOST=redis
    depends_on:
      - db
      - mailhog
      - memcached
      - redis
    restart: unless-stopped
    volumes:
      - ./:/workspace

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    restart: unless-stopped

  memcached:
    image: memcached:1.5-alpine
    restart: unless-stopped

  redis:
    image: redis:4-alpine
    restart: unless-stopped
    volumes:
      - redis:/data

  web:
    image: nginx:stable
    depends_on:
      - app
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./:/workspace
      - ./templates/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db:
  redis:
