version: '3.4'

services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_PASSWORD=${DB_PASSWORD}

  app:
    image: datashaman/larabuild:build
    environment:
      - CACHE_DRIVER=memcached
      - DB_HOST=db
      - MEMCACHED_HOST=memcached
      - QUEUE_CONNECTION=beanstalkd
      - QUEUE_HOST=beanstalkd
      - REDIS_HOST=redis
      - SESSION_DRIVER=redis
    depends_on:
      - beanstalkd
      - db
      - redis
    volumes:
      - storage:/workspace/app/storage

  web:
    image: nginx:stable
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - storage:/workspace/app/storage

  worker:
    build: .
    command: php artisan queue:work --tries=1 -vvv
    env_file: .env
    environment:
      - CACHE_DRIVER=memcached
      - DB_HOST=db
      - MEMCACHED_HOST=memcached
      - QUEUE_CONNECTION=beanstalkd
      - QUEUE_HOST=beanstalkd
      - REDIS_HOST=redis
      - SESSION_DRIVER=redis
    depends_on:
      - beanstalkd
      - db
      - redis
    volumes:
      - ./:/workspace/app

  beanstalkd:
    image: schickling/beanstalkd

  beanstalkd-console:
    image: schickling/beanstalkd-console
    command: php -S 0.0.0.0:2080 -t /source/public
    environment:
      - BEANSTALK_SERVERS=beanstalkd:11300
    ports:
      - 2080:2080
    depends_on:
      - beanstalkd

  memcached:
    image: memcached:alpine

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  redis:
  storage:
